apiVersion: v1
kind: Pod
metadata:
  name: ubuntu2
  namespace: bk21
  labels:
    app: ubuntu2
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu-container
  restartPolicy: Always
