apiVersion: v1
kind: Pod
metadata:
  name: Ubuntu
  namespace: default
  labels:
    app: ubuntu
spec:
  containers:
  - image: nginx
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
