apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    app: ubuntu
spec:
  containers:
  - image: busybox
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
